#!/bin/bash
set -x
set +e

REVISION=${DRONE_COMMIT_SHA:0:15}
HASH=$(echo -n $DRONE_BRANCH_FROM_QAINIT | md5sum | awk '{print $1}')
DEPLOY_ID=${HASH:0:8}
ENV=qa


# Check if artifact esists for current branch
aws s3 ls s3://prima-artifacts-encrypted/microservices/pyxis/${REVISION}-${DEPLOY_ID}-${ENV}.tar.gz

if [[ $? -eq 0 ]]; then
  echo "Artifact already exists!"
  exit 0
fi

set -e

# Create artifact
# TODO?
# git submodule update --init
# cp .env.dist.qa .env
yarn run release
tar czf ${REVISION}-${DEPLOY_ID}-${ENV}.tar.gz -C dist .


aws --region="eu-west-1" s3 cp ${REVISION}-${DEPLOY_ID}-${ENV}.tar.gz s3://prima-artifacts-encrypted/microservices/pyxis/${REVISION}-${DEPLOY_ID}-${ENV}.tar.gz
