#!/bin/bash

set -x
set +e

export AWS_DEFAULT_REGION=eu-west-1
REVISION=${DRONE_COMMIT_SHA:0:15}
HASH=$(echo -n $DRONE_BRANCH_FROM_QAINIT | md5sum | awk '{print $1}')
DEPLOY_ID=${HASH:0:8}
STACK_NAME="ecs-task-pyxis-qa-${HASH}"
ALB_NAME="pyxis-qa-${HASH}"

ACTION=""

if ! aws --region="eu-west-1" cloudformation describe-stacks --stack-name "${STACK_NAME}" >/dev/null; then
  ACTION="create-stack"
else
  ACTION="update-stack"
  STACK_REVISION=$(aws cloudformation describe-stacks --stack-name "${STACK_NAME}" | jq '.Stacks[0].Parameters[] | select(.ParameterKey=="ReleaseVersion") | .ParameterValue')
  if [[ "$STACK_REVISION" = '"'$REVISION'-'$DEPLOY_ID'"' ]]; then
    echo "Latest version already deployed"
    exit 0
  fi
fi

aws --region="eu-west-1" cloudformation "${ACTION}" --stack-name "${STACK_NAME}" \
--template-body file://"${PWD}"/deploy/task.yml \
--parameters ParameterKey=ReleaseVersion,ParameterValue="${REVISION}-${DEPLOY_ID}" \
ParameterKey=Environment,ParameterValue=qa \
ParameterKey=EnvHash,ParameterValue="${HASH}" \
ParameterKey=ECSClusterName,ParameterValue="${ECS_CLUSTER_NAME}" \
ParameterKey=HostnamePattern,ParameterValue="pyxis-${HASH}.qa.colaster.com" \
ParameterKey=HostnamePatternPriority,ParameterValue=62 \
ParameterKey=ALBShortName,ParameterValue="${ALB_NAME:0:27}" \
--role-arn="${ROLE_ARN}" \
--tags Key=qainit,Value="${DRONE_BRANCH_FROM_QAINIT}"
